"""Add ApiKey and LlmCallLog models

Revision ID: 18635f110499
Revises: b35ab6f2951c
Create Date: 2026-05-03 12:53:46.665373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18635f110499'
down_revision: Union[str, Sequence[str], None] = 'b35ab6f2951c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_call_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('agent_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_call_logs_id'), 'llm_call_logs', ['id'], unique=False)
    op.create_index(op.f('ix_llm_call_logs_provider'), 'llm_call_logs', ['provider'], unique=False)
    op.add_column('api_keys', sa.Column('key_value', sa.String(), nullable=True))
    op.add_column('api_keys', sa.Column('alias', sa.String(), nullable=True))
    op.add_column('api_keys', sa.Column('provider', sa.String(), nullable=True))
    op.add_column('api_keys', sa.Column('is_active', sa.Integer(), nullable=True))
    op.add_column('api_keys', sa.Column('rate_limit_reset_at', sa.DateTime(), nullable=True))
    op.add_column('api_keys', sa.Column('calls_today', sa.Integer(), nullable=True))
    op.add_column('api_keys', sa.Column('tokens_today', sa.Integer(), nullable=True))
    op.add_column('api_keys', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('api_keys', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_api_keys_provider'), 'api_keys', ['provider'], unique=False)
    op.drop_column('api_keys', 'key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('key', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_api_keys_provider'), table_name='api_keys')
    op.drop_column('api_keys', 'updated_at')
    op.drop_column('api_keys', 'created_at')
    op.drop_column('api_keys', 'tokens_today')
    op.drop_column('api_keys', 'calls_today')
    op.drop_column('api_keys', 'rate_limit_reset_at')
    op.drop_column('api_keys', 'is_active')
    op.drop_column('api_keys', 'provider')
    op.drop_column('api_keys', 'alias')
    op.drop_column('api_keys', 'key_value')
    op.drop_index(op.f('ix_llm_call_logs_provider'), table_name='llm_call_logs')
    op.drop_index(op.f('ix_llm_call_logs_id'), table_name='llm_call_logs')
    op.drop_table('llm_call_logs')
    # ### end Alembic commands ###
